apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-dataset-harvester-etl
  name: fdk-dataset-harvester-etl
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataset-harvester-etl
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-dataset-harvester-etl
    spec:
      containers:
      - env:
        - name: TO_BE_UPDATED
          value: {{ required "Missing value TO_BE_UPDATED" .Values.TO_BE_UPDATED | quote }}
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: MONGO_PASSWORD
        - name: NAMESPACE
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: fdk-dataset-harvester-etl
        resources:
          requests:
            memory: {{ required "Missing value FDK_DATASET_HARVESTER_ETL_MEMORY" .Values.FDK_DATASET_HARVESTER_ETL_MEMORY | quote }}
      restartPolicy: Always
status: {}
